# Generated by Django 2.2 on 2021-01-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20201201_0557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'managed': False, 'verbose_name_plural': 'Order details'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': False, 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False, 'verbose_name_plural': 'Products'},
        ),
    ]
