version: '3'

services:
  sqlserver:
    build: sqlserver
  web:
    build: web
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - sqlserver
    command: ["./wait-for-it.sh", "sqlserver:1433", "-t", "40", "--", "python3", "manage.py", "runserver", "0.0.0.0:8000"]